### ISSUE TITLE
FAQ: Difference from other best practice programmes?

### ISSUE THREAD

**Issue by silverhook** [Open-Source-Compliance/Sharing-creates-value#21]
It would be great to have in the FAQ (or even `README.md`) how this differs from other similar programmes, like e.g.:

- [OpenChain](https://wiki.linuxfoundation.org/openchain/start)
- [Open Compliance Program](https://compliance.linuxfoundation.org)
- [Copyleft.org](http://copyleft.org/)

**Comment by OliverFendt** [comment]
thank you for the hint.
the main difference is that this is an effort for everybody providing real know how how things in the area of OSS compliance can be done.
OpenChain is currently more focusing on training and assessment, but the topic "how do I xyz to be license compliant" is not touched at all. As far as I know the answer to the question is a "legal interpretation of a certain screnario" and OpenChain does not want to do legal interpretations. The same applies for the Open Compliance Program of the Linux Foundation. Copyleft.org provides practical tipps but it does not provide any license information and copyright notices of OSS packages, and this is a major objective of this project to provide such kind of information - ready to use for everybody under a very relaxed license. Thus making OSS compliance for everybody a low effort and easy task.
Is it a bit more clear? If so I will add this statement to the Readme.md

**Comment by silverhook** [comment]
Yes, this explains it quite a bit more. If you could include something like that in the readme, it’d be great.

**Comment by OliverFendt** [comment]
The explanation was added to the Readme file

**Comment by silverhook** [comment]
+1 Great
