### ISSUE TITLE
Add REUSE to big picture

### ISSUE THREAD

**Issue by mxmehl** [Open-Source-Compliance/Sharing-creates-value#75]
As recently discussed in Brussels, I would like to suggest to add [REUSE](https://reuse.software) to the (by the way great!) tooling landscape graphic.

I think the project is a solution for some of the described areas. For example:

* Inbound: REUSE compliant software greatly improves the reuasbility of its code.
* Compliance checker
* Component Analysis Service
* CI/CD
* FOSS Compliance Artefact Generator (`reuse spdx` for a BoM)
* License & Copyright Scanner (searching for license identifiers and copyright statements)
* Outbound: if the resulting shared/published code is REUSE compliant, the inbound for another party is also much easier to understand with regard to licensing and copyright

**Comment by OliverFendt** [comment]
Hi Max
thank you for the suggestion. Would you mind to make a proposal where REUSE is best located in the big picture? 
I think more in having an extra inbound arrow or a tag with REUSE on the current existing arrow and perhaps add "preferred". Because REUSE conformant inbound software will not necessarily make the other steps obsolete. But it will enable the complete automation.

**Comment by mxmehl** [comment]
In my first post I've made a few proposals. However, as I lack some insight in full-blown compliance processes my estimation might not be correct and/or match the full expectations for these tasks.

I agree on adding some additional note in the inbound arrow, something along the lines of "preferably/ideally REUSE compliant".

As for the picture, you can choose from our [CI repo](https://git.fsfe.org/reuse/reuse-ci). I would recommend the standard [reuse.png](https://git.fsfe.org/reuse/reuse-ci/raw/branch/master/reuse.png).

**Comment by OliverFendt** [comment]
I added the reuse logo to the big picture, please check Sharing-creates-value/Templates/Toolchain-big-picture-abstract-and-instance-example-5.0.pptx
