### ISSUE TITLE
Menu of Existing OSS Tools too long

### ISSUE THREAD

**Issue by mxmehl** [Open-Source-Compliance/Sharing-creates-value#92]
Even on a screen 1080p high, the list of tools in the menu of [this page](https://oss-compliance-tooling.org/Tooling-Landscape/OSS-Based-License-Compliance-Tools/) is too long. On my screen, "OSS Discovery by OpenLogic" is the last item I can fully see.

I am not sure how this can be achieved, but ideally the menu should be scrollable as well or be organised in two columns.

**Comment by OliverFendt** [comment]
Thank @mxmehl for pointing this out, I will check how to fix it and fix it

**Comment by OliverFendt** [comment]
fixed I switched to an other theme and a newer mkdocs version.
Check it at https://oss-compliance-tooling.org/

**Comment by mxmehl** [comment]
Excellent, thank you!
